version: '3.1'
services:
  # postgres:
  #   image: postgres:12
  #   container_name: postgres_container
  #   env_file:
  #     - .env
  #   ports:
  #     - "${POSTGRES_PORT}:5432"
  #   restart: always
  #   networks:
  #     - common
  #   volumes:
  #     - postgres_data:${PGDATA}
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DATABASE=${POSTGRES_DATABASE}
  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   ports:
  #     - '6379:6379'
  #   command: redis-server --requirepass ${REDIS_PASSWORD} --loglevel warning
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - common
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
      - '8001:8001'
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD} --loglevel warning"
    networks:
      - common
  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - common
  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - common

networks:
  common:
    driver: bridge

volumes:
  postgres_data:
  # redis_data:
  mysql_data: